version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_NAME: tareas
      DB_USER: root
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mysql

  mysql:
    image: mysql:latest
    container_name: mysql_exam
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: tareas
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_incident_app:/var/lib/mysql

volumes:
  mysql_incident_app:
